version: '3.8'

services:
  db:
    image: postgres:14-alpine # Using a specific, lightweight version is good practice
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}