# .github/workflows/ci.yml
name: Ruby on Rails CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: salary_payment_file_exporter_test
        ports:
          - 5432:5432
        # Health check to ensure postgres is ready to accept connections
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version-file: '.ruby-version'
          bundler-cache: true # This will run `bundle install` and cache gems

      - name: Set up Test Database
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run RSpec tests
        run: bundle exec rspec